# Generated by Django 4.2.8 on 2023-12-15 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('trade_brand', models.CharField(max_length=256, verbose_name='Brand')),
                ('country', models.CharField(max_length=256, verbose_name='Country')),
                ('country_brand_registration', models.CharField(max_length=256, verbose_name='Country of brand registration')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description_short', models.CharField(blank=True, max_length=256, null=True, verbose_name='Short description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('product_code', models.PositiveIntegerField(unique=True, verbose_name='Product code')),
                ('stock', models.CharField(choices=[('I', 'In stock'), ('N', 'Not available'), ('W', 'Withdrawn from sale'), ('A', 'Awaiting')], default='I', max_length=1, verbose_name='Stock')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='Image path')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.category', verbose_name='Categories')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_charactetistic', models.CharField(max_length=256, verbose_name='Product characteristics')),
                ('categories', models.ManyToManyField(blank=True, db_table='', related_name='characteristic_categories', to='product.category')),
            ],
            options={
                'verbose_name': 'Product characteristic',
                'verbose_name_plural': 'Product characteristics',
                'db_table': 'product characteristic',
            },
        ),
        migrations.CreateModel(
            name='TypeProductCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type_characteristic', models.CharField(max_length=256, verbose_name='Type of product characteristics')),
                ('product', models.ManyToManyField(db_table='type product m2m', related_name='types_product', to='product.product')),
                ('product_characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_product', to='product.productcharacteristics')),
            ],
            options={
                'verbose_name': 'Type of product characteristics',
                'verbose_name_plural': 'Types of product characteristics',
                'db_table': 'type characteristics',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='Image path')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='price_is_positive', violation_error_message='Price must be positive or empty.'),
        ),
    ]
