# Generated by Django 4.2.8 on 2023-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristics',
            name='product',
            field=models.ManyToManyField(db_table=' product characteristic m2m', related_name='product_characteristics', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='category characteristic m2m', related_name='characteristic_categories', to='product.category'),
        ),
    ]
