# Generated by Django 4.2.8 on 2023-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcharacteristics_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product',
            field=models.ManyToManyField(blank=True, db_table=' product characteristic m2m', related_name='product_characteristics', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product_charactetistic',
            field=models.CharField(max_length=256, unique=True, verbose_name='Product characteristics'),
        ),
        migrations.AlterField(
            model_name='typeproductcharacteristics',
            name='product',
            field=models.ManyToManyField(blank=True, db_table='type product m2m', related_name='types_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='typeproductcharacteristics',
            name='type_characteristic',
            field=models.CharField(max_length=256, unique=True, verbose_name='Type of product characteristics'),
        ),
    ]
