# Generated by Django 4.2.8 on 2023-12-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=256, unique=True, verbose_name='Product code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='example-default-slug', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
