# Generated by Django 4.2.8 on 2024-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_code_alter_product_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gte', 0)), name='discount_percentage_is_positive', violation_error_message='Discount percentage must be positive or 0.'),
        ),
    ]
