# Generated by Django 4.2.8 on 2024-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_code_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristics',
            old_name='product_charactetistic',
            new_name='product_characteristic',
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product',
            field=models.ManyToManyField(blank=True, db_table='product characteristic m2m', related_name='product_characteristics', to='product.product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gte', 0)), name='discount_percentage_is_positive', violation_error_message='Discount percentage must be positive or 0.'),
        ),
    ]
