# Generated by Django 4.2.8 on 2024-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_charactetistic_productcharacteristics_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This field allows empty value', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
