# Generated by Django 4.2.8 on 2024-01-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_price'),
        ('product', '0007_alter_category_level'),
    ]

    operations = [
    ]
