# Generated by Django 4.2.8 on 2024-01-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristics',
            old_name='product_charactetistic',
            new_name='product_characteristic',
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='product',
            field=models.ManyToManyField(blank=True, db_table='product characteristic m2m', related_name='product_characteristics', to='product.product'),
        ),
    ]
