# Generated by Django 4.2.8 on 2024-03-30 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_discount_percentage_is_positive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='rating_from_0_to_5_or_null',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter a rating between 0 and 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='rating_from_0_to_5', violation_error_message='Rating must has to equal from 0 to 5.'),
        ),
    ]
