# Generated by Django 4.2.8 on 2024-03-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_rating_from_0_to_5_or_null_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
