# Generated by Django 4.2.8 on 2024-04-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Additional Product Image', 'verbose_name_plural': 'Additional Product Images'},
        ),
    ]
