# Generated by Django 4.2.11 on 2024-04-23 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productimage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristics',
            old_name='product_characteristic',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typeproductcharacteristics',
            old_name='type_characteristic',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter a rating between 0 and 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Rating cannot be less than 0'), django.core.validators.MaxValueValidator(5, message='Rating cannot be more than 5')], verbose_name='Rating'),
        ),
    ]
