# Generated by Django 4.2.11 on 2024-04-25 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productcharacteristics_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_special_characters', message='Special characters are not allowed.', regex='^[a-zA-Z0-9]+$')], verbose_name='Product code'),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Product characteristic'),
        ),
        migrations.AlterField(
            model_name='typeproductcharacteristics',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Type of product characteristic'),
        ),
    ]
