version: '3'

services:
  db:
    image: postgres:13.1-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/ecommerce_backend
      - static_volume:/ecommerce_backend/static
      - media_volume:/ecommerce_backend/media
    expose:
      - 8000
    networks:
      - ecommerce_network
    depends_on:
      - db

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/ecommerce_backend/static
      - media_volume:/ecommerce_backend/media
    ports:
      - "80:80"
    networks:
      - ecommerce_network
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge
