version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPORT=${DB_PORT}
    volumes:
      - postgres_:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/ecommerce_backend
      - static_volume:/ecommerce_backend/static
      - media_volume:/ecommerce_backend/media
    expose:
      - 8000
    networks:
      - ecommerce_network
    depends_on:
      - db

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    volumes:
      - static_volume:/ecommerce_backend/static
      - media_volume:/ecommerce_backend/media
    ports:
      - "80:80"
    networks:
      - ecommerce_network
    depends_on:
      - web
      - cache

  cache:
    restart: unless-stopped
    build:
      context: .
      dockerfile: config/redis/Dockerfile
    env_file:
      - ./.env
    networks:
      - ecommerce_network
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  static_volume:
  media_volume:
  postgres_:
  redis_data:

networks:
  ecommerce_network:
    driver: bridge
