# Generated by Django 4.2.8 on 2024-04-08 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Item quantity'),
        ),
    ]
