# Generated by Django 4.2.8 on 2024-02-17 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_category_slug'),
        ('order', '0009_alter_delivery_option_alter_order_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Warehouse Item',
                'verbose_name_plural': 'Warehouse Items',
                'db_table': 'warehouse_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('total_balance', models.IntegerField(default=0, help_text='The quantity of the product in the warehouse', verbose_name='Total balance')),
                ('is_active', models.BooleanField(default=True)),
                ('product_name', models.ForeignKey(help_text='The name of the product stored in warehouse', on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product name')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(help_text='The order for which the product is reserved', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('warehouse_item', models.ForeignKey(help_text='Product reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='warehouse.warehouseitem')),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reserves',
                'db_table': 'reserve',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('document', models.CharField(help_text='Consignment note', max_length=100)),
                ('consumption_type', models.CharField(choices=[('order', 'Order'), ('write-off', 'Write-off')], help_text='Type of consumption', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Additional comments', max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse_item', models.ForeignKey(help_text='Product consumed', on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='warehouse.warehouseitem')),
            ],
            options={
                'verbose_name': 'Goods Consumption',
                'verbose_name_plural': 'Goods Consumptions',
                'db_table': 'goods_consumption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsArrival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('document', models.CharField(help_text='Consignment note', max_length=100)),
                ('arrival_type', models.CharField(choices=[('arrival', 'Arrival'), ('return', 'Return'), ('inventory', 'Inventory')], help_text='type of arrival', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Additional comments', max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse_item', models.ForeignKey(help_text='Product arrived', on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='warehouse.warehouseitem')),
            ],
            options={
                'verbose_name': 'Goods Arrival',
                'verbose_name_plural': 'Goods Arrivals',
                'db_table': 'goods_arrival',
                'ordering': ['-created_at'],
            },
        ),
    ]
