# Generated by Django 4.2.8 on 2024-02-20 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(help_text='Consignment note number', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Number should be 11 to 13 digits', regex='^\\d{11,13}$')])),
                ('sign_date', models.DateField(help_text='Date of signing the consignment note')),
            ],
            options={
                'verbose_name': 'Consignment Note',
                'verbose_name_plural': 'Consignment Notes',
                'db_table': 'consignment_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='goodsarrival',
            name='warehouse_item',
        ),
        migrations.RemoveField(
            model_name='goodsconsumption',
            name='warehouse_item',
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='warehouseitem',
            index=models.Index(fields=['-created_at'], name='warehouse_i_created_77f1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseitem',
            index=models.Index(fields=['content_type'], name='warehouse_i_content_f56a62_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentnote',
            index=models.Index(fields=['sign_date'], name='idx_consignment_note_sign_date'),
        ),
        migrations.AlterUniqueTogether(
            name='consignmentnote',
            unique_together={('number', 'sign_date')},
        ),
        migrations.AlterField(
            model_name='goodsarrival',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_arrival', to='warehouse.consignmentnote'),
        ),
        migrations.AlterField(
            model_name='goodsconsumption',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods_consumption', to='warehouse.consignmentnote'),
        ),
    ]
