# Generated by Django 4.2.8 on 2024-02-29 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_consignmentnote_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentnote',
            name='number',
            field=models.CharField(help_text='Consignment note number. Note that this field accepts letters and other characters.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity of the product', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity of the product', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
