# Generated by Django 4.2.8 on 2024-02-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_consignmentnote_remove_goodsarrival_warehouse_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsarrival',
            name='document',
        ),
        migrations.RemoveField(
            model_name='goodsconsumption',
            name='document',
        ),
        migrations.AddField(
            model_name='consignmentnote',
            name='goods_arrival',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignment_note', to='warehouse.goodsarrival'),
        ),
        migrations.AddField(
            model_name='consignmentnote',
            name='goods_consumption',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignment_note', to='warehouse.goodsconsumption'),
        ),
    ]
