# Generated by Django 4.2.11 on 2024-03-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_discount_percentage'),
        ('warehouse', '0003_alter_consignmentnote_number_alter_reserve_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_item',
            field=models.ForeignKey(help_text='Order item related to this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.orderitem'),
        ),
    ]
