# Generated by Django 4.2.8 on 2024-02-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_goodsarrival_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentnote',
            name='goods_arrival',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.goodsarrival'),
        ),
        migrations.AlterField(
            model_name='consignmentnote',
            name='goods_consumption',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.goodsconsumption'),
        ),
    ]
