# Generated by Django 4.2.8 on 2024-02-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_slug'),
        ('warehouse', '0004_alter_consignmentnote_goods_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='product_name',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(default='', help_text='The product stored in warehouse', on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
