# Generated by Django 4.2.11 on 2024-03-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_transaction_order_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Goods Transaction', 'verbose_name_plural': 'Goods Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='consignment_note',
            field=models.ForeignKey(blank=True, help_text='Note that this field may be blank.', null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.consignmentnote'),
        ),
    ]
