# Generated by Django 4.2.11 on 2024-03-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_options'),
        ('product', '0009_alter_category_slug'),
        ('warehouse', '0005_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Order item related to this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(help_text='The product stored in warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='product.product', verbose_name='Product'),
        ),
    ]
