# Generated by Django 4.2.8 on 2024-01-23 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('N', 'NEW'), ('P', 'Processing'), ('S', 'Sent'), ('D', 'Delivered'), ('E', 'Executed'), ('C', 'Canceled'), ('R', 'Returned'), ('I', 'Issue')], default='N', verbose_name='Status')),
                ('first_name', models.CharField(max_length=250, verbose_name='First name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('phone', models.CharField(max_length=17, verbose_name='Mobile phone')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
