# Generated by Django 4.2.8 on 2024-01-30 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+38(050)111-11-11'. Up to 17 digits allowed.", regex='^\\+\\d{2}\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Mobile phone'),
        ),
    ]
