# Generated by Django 4.2.8 on 2024-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_number_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
