# Generated by Django 4.2.8 on 2024-02-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_delivery_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='option',
            field=models.CharField(choices=[('D', 'Delivery'), ('С', 'Сourier')], default='С', verbose_name='Delivery option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='order.delivery'),
        ),
    ]
