# Generated by Django 4.2.8 on 2024-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_delivery_flat_alter_delivery_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='entrance',
            field=models.CharField(blank=True, help_text='This field can take text. Example: Entrance to a toy store', null=True, verbose_name='Entrance'),
        ),
    ]
