# Generated by Django 4.2.8 on 2024-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_delivery_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='option',
            field=models.CharField(choices=[('D', 'Delivery'), ('C', 'Courier')], default='C', max_length=250, verbose_name='Delivery option'),
        ),
    ]
